### ISSUE TITLE
PEN-1100.3.6c-Extended As a pool owner/user I want to be able to select and control pre-programmed lighting effects.

### ISSUE THREAD

**Issue by sevennote** [gryz/THW-Update-Needed#1]
https://pathfinder.atlassian.net/wiki/x/dICwB

klewis03[ 4:00 PM ] QA1 right?
adam[ 4:00 PM ] yeah
klewis03[ 4:00 PM ] I ran your command and I get back a 400 in local mode
adam[ 4:00 PM ] it seems to be staying on status off
[ 4:01 ] getting a 200 though
[ 4:01 ] 
```
Sending: '{"command":"SETPARAMLIST","objectList":[{"objnam":"CD6DC","params":{"STATUS":"ON"}}],"messageID":"0e61e864-a1e0-4d74-b287-6abfcf61ea19"}' : Tue Jul 05 2016 15:57:25 GMT-0500 (CDT)
2016-07-05 15:57:26.141 SocketService.js:91 Receiving: {
    "command": "NotifyList",
    "messageID": "5fcb382c-470e-48ad-9791-35ecf25e5200",
    "objectList": [
        {
            "objnam": "CD6DC",
            "params": {
                "STATUS": "ON"
            }
        }
    ]
}: Tue Jul 05 2016 15:57:26 GMT-0500 (CDT)
2016-07-05 15:57:26.144 SocketService.js:91 Receiving: {"command":"SetParamList","messageID":"0e61e864-a1e0-4d74-b287-6abfcf61ea19","response":"200"}
```
klewis03[ 4:02 PM ] ahhh it was missing the message id
adam[ 4:03 PM ] oh right, the .net server generates a message id, when I am testing against the .net server I don’t need to pass the message id.
klewis03[ 4:03 PM ] it looks like you are getting the notify of ON
[ 4:04 ] 2016-07-05 15:57:26.141 SocketService.js:91 Receiving: {
   "command": "NotifyList",
   "messageID": "5fcb382c-470e-48ad-9791-35ecf25e5200",
   "objectList": [
       {
           "objnam": "CD6DC",
           "params": {
               "STATUS": "ON"
           }
       }
   ]
}: Tue Jul 05 2016 15:57:26 GMT-0500 (CDT)
adam[ 4:04 PM ] but not for the child light CE6D2
klewis03[ 4:05 PM ] did you subscribe to the light circuits statuses directly?
[ 4:05 ] to get a notify you must subscribe to the parameters of the object you wish to be notified about upon change
adam[ 4:08 PM ] yes it should be subscribed, when I try to do the opposite, turn if off, I get a notify for both the light group and the lights.
also if I was to refresh the page, if it wasn’t notifying for some reason, the light is still showing as off so it doesn’t seem to be updating
klewis03[ 4:09 PM ] hmm I will have a dev look into it
adam[ 4:09 PM ] cool, thanks

Update AC per table in the specs and it is baked.
6/20/2016 - on the frontend lets make sure that the installer can't make a group with invalid combinations, e.g. a group with a dimmer and regular light.

**Comment by klewis77** [comment]
This was fixed in an update last week but was not deployed. I will get request response messages up once I have them

**Comment by klewis77** [comment]
Deployed to DEV1 for verification

**Comment by acarnagey** [comment]
There is an issue with group colors, setting USE 404's for the group and ACT doesn't show up for light in group. The group chat on July 5th talks about this and is also mentioned in the wiki page dev notes.

**Comment by klewis77** [comment]
@acarnagey 

Should the new issue be filed under a new bug? This particular issue should have been resolved. I am working on getting the responses from the THW for this  issue.

**Comment by acarnagey** [comment]
@klewis77 I think we have it grouped by story.  @gryz should we create a new issue since it is another THW for the same story?

**Comment by klewis77** [comment]
On DEV1

**Request**
```json
{
    "command": "RequestParamList", 
    "messageID": "10A86ef1-88f1-8091-7cdf1c", 
    "objectList": [
        {
            "objnam": "CC442", 
            "keys": [
                "STATUS"
            ]
        }, 
        {
            "objnam": "CD94A", 
            "keys": [
                "STATUS"
            ]
        }
    ]
}
```

**Reponse to Request**
```json
{
    "command": "NotifyList",
    "messageID": "10A86ef1-88f1-8091-7cdf1c",
    "timeSince": "0",
    "timeNow": "948333703",
    "response": "200",
    "objectList": [
        {
            "objnam": "CC442",
            "params": {
                "STATUS": "ON"
            }
        },
        {
            "objnam": "CD94A",
            "params": {
                "STATUS": "ON"
            }
        }
    ]
}
```

**Change STATUS to ON for the Light Group Object**
```json
{
    "command": "SetParamList", 
    "messageID": "10A86ef1-88f1-8091-7cdf1f", 
    "objectList": [
        {
            "objnam": "CC442", 
            "params": {
                "STATUS": "ON"
            }
        }
    ]
}
```

**Response to STATUS to ON**
```json
{
    "command": "NotifyList",
    "messageID": "5daacaaa-5de0-49fb-9de6-8e4181e14e67",
    "objectList": [
        {
            "objnam": "CD94A",
            "params": {
                "STATUS": "DLYON"
            }
        }
    ]
}
{
    "command": "NotifyList",
    "messageID": "5bd0991c-1830-4397-a634-96dc88789da9",
    "objectList": [
        {
            "objnam": "CC442",
            "params": {
                "STATUS": "ON"
            }
        }
    ]
}
{
    "command": "NotifyList",
    "messageID": "9861f17b-e227-4ea1-8290-41b1980feb88",
    "objectList": [
        {
            "objnam": "CD94A",
            "params": {
                "STATUS": "ON"
            }
        }
    ]
}
```

**Comment by acarnagey** [comment]
I moved the other one over to another ticket.
