### ISSUE TITLE
PEN-1000.4.1a As a pool owner/user I need to be able to add, configure, and reconfigure intelliflow VF pumps within the installation.  AND PEN-1000.4.1b As a pool owner/user I need to be able to add/remove/configure intelliflow VS pumps within the installation so I can define pump name

### ISSUE THREAD

**Issue by sevennote** [gryz/THW-Update-Needed#10]
https://pathfinder.atlassian.net/wiki/x/xwDzB
https://pathfinder.atlassian.net/wiki/x/ywDzB

adam[ 12:23 PM ] 
@klewis03: we noticed that the THW response for object affects for creating and editing was off.
For example the .net server gets
```
{
    "command": "CreateObjectAffect",
    "messageID": ":d84948aa-d475-4e71-bf65-70d45ceac59c",
    "response": "200",
    "objectList": [ ...
```
where the response is supposed to be like https://pathfinder.atlassian.net/wiki/display/PEN/Create+Object+Affect
```
{
    "command": "SetCommand", 
    "messageID": "10A86ef1-88f1-8091-7cdf2b", 
    "method": "CreateObjectAffect", 
    "response": "200", 
    "objectList": [ ...
```
command needs to be SetCommand and method needs to be CreateObjectAffect or EditObjectAffect basically.  Thats why we weren’t getting a response back from the .net server. (edited)
klewis03[ 12:52 PM ] 
so when you do the request in the new way it works?
[ 12:53 ] 
thats a good catch
Need to make a call for the list of available addresses to assign.
Can both type and use + - on times and flow values.
On added circuits, the flow rate is not a drop down it is an enterable value and a + - control.
If circuit item type is static, can't remove it, so don't show the checkbox to do so.

**Comment by gryz** [comment]
Asked to check for working by Keith.

**Comment by acarnagey** [comment]
Functionally this does what it should, but the response format is off so I had to confirm that it is still off based on the API documentation specs, with the response format off, the .net server doesn’t return a response so the web client never gets a response.

**Comment by klewis77** [comment]
We will be fixing the malformed responses here shortly and get an Update to DEV1 for validation on your side. Once we do our testing I will post the request and responses up here

**Comment by gryz** [comment]
Keith,

To be fair, is this fixed right now or not?

If it's fixed and testable then it gets the fixed tag, if it's not then it does not get the tag.

Best wishes,

Larry

**Comment by acarnagey** [comment]
I verified it, something like this should be sufficient since it is pointing to pentdev
<img width="1903" alt="screen shot 2016-07-12 at 2 55 32 pm" src="https://cloud.githubusercontent.com/assets/1028600/16781421/d1852be4-4840-11e6-9281-438b700040b1.png">
