### ISSUE TITLE
SendQuery Responses missing ‘queryName’ parameter. 

### ISSUE THREAD

**Issue by gryz** [gryz/THW-Update-Needed#12]
The API documentation specifies that each GetQuery request requires a SendQuery response that includes the following parameters (command, response, messageID, answer and queryName). However, queryName is missing from the payload.

**Comment by gryz** [comment]
Keith,

As we discussed, some kind of test evidence would be useful to demostrate that the issue is indeed fixed.

Can you provide such output from your web tool for this issue?

Best Wishes,

Larry

**Comment by klewis77** [comment]
We did a revivification everything looks ok on our side.

**Comment by Dashon** [comment]
I was able to verify the message coming from the THW correctly. The issue was Server side, One commit did not push ('Update SendQueryResponse')
