### ISSUE TITLE
PEN-1000.5.1.1 As a pool owner/user I need to be able to customize the IS4 remote panel. (ENABLE broke)

### ISSUE THREAD

**Issue by acarnagey** [gryz/THW-Update-Needed#14]
Turning one IS4 to enable OFF turns both OFF, turning one IS4 to enable ON turns both OFF.

Sending: '{"command":"SetCommand","method":"EditRemote","arguments":[{"objnam":"RAAF7","params":{"SNAME":"IS4 Remote 128","SUBTYP":"IS4",**"ENABLE":"OFF",**"BUTTONS":[{"OBJNAM":"b61C5","LISTORD":"1","CIRCUIT":"00000"},{"OBJNAM":"b15FB","LISTORD":"2","CIRCUIT":"00000"},{"OBJNAM":"b7F68","LISTORD":"3","CIRCUIT":"00000"},{"OBJNAM":"b9BCA","LISTORD":"4","CIRCUIT":"00000"}]}}],"messageID":"e73e4ba0-5e97-42b5-a006-c94bf7d3c1c7"}' 

Receiving: {"response":"200","objectList":[],"command":"SetCommand","messageID":"e73e4ba0-5e97-42b5-a006-c94bf7d3c1c7"}

Sending:'{"command":"GetQuery","queryName":"GetRemotes","arguments":"","messageID":"d5470e0d-46fa-49ed-8377-23733a80402c"}'

Receiving: {"answer":[{"objnam":"R8F45","params":{"SUBTYP":"IS4","SNAME":"IS4 Remote 129","COMUART":"COMUART","MODULE":"MODULE","LISTORD":"129","BODY":"BODY","PUMP":"PUMP",**"ENABLE":"OFF"**,"MODE":"MODE","BUTTONS":[{"objnam":"bA21B","params":{"OBJNAM":"bA21B","LISTORD":"4","PARENT":"R8F45","CIRCUIT":"00000"}},{"objnam":"bDA73","params":{"OBJNAM":"bDA73","LISTORD":"3","PARENT":"R8F45","CIRCUIT":"00000"}},{"objnam":"b7EA6","params":{"OBJNAM":"b7EA6","LISTORD":"2","PARENT":"R8F45","CIRCUIT":"00000"}},{"objnam":"b6970","params":{"OBJNAM":"b6970","LISTORD":"1","PARENT":"R8F45","CIRCUIT":"00000"}}]}},{"objnam":"RAAF7","params":{"SUBTYP":"IS4","SNAME":"IS4 Remote 128","COMUART":"COMUART","MODULE":"MODULE","LISTORD":"128","BODY":"BODY","PUMP":"PUMP","**ENABLE":"OFF**","MODE":"MODE","BUTTONS":[{"objnam":"b9BCA","params":{"OBJNAM":"b9BCA","LISTORD":"4","PARENT":"RAAF7","CIRCUIT":"00000"}},{"objnam":"b7F68","params":{"OBJNAM":"b7F68","LISTORD":"3","PARENT":"RAAF7","CIRCUIT":"00000"}},{"objnam":"b15FB","params":{"OBJNAM":"b15FB","LISTORD":"2","PARENT":"RAAF7","CIRCUIT":"00000"}},{"objnam":"b61C5","params":{"OBJNAM":"b61C5","LISTORD":"1","PARENT":"RAAF7","CIRCUIT":"00000"}}]}}],"command":"SendQuery","messageID":"d5470e0d-46fa-49ed-8377-23733a80402c","response":"200"}

Sending: '{"command":"SetCommand","method":"EditRemote","arguments":[{"objnam":"R8F45","params":{"SNAME":"IS4 Remote 129","SUBTYP":"IS4",**"ENABLE":"ON"**,"BUTTONS":[{"OBJNAM":"b6970","LISTORD":"1","CIRCUIT":"00000"},{"OBJNAM":"b7EA6","LISTORD":"2","CIRCUIT":"00000"},{"OBJNAM":"bDA73","LISTORD":"3","CIRCUIT":"00000"},{"OBJNAM":"bA21B","LISTORD":"4","CIRCUIT":"00000"}]}}],"messageID":"4edc3db9-7c98-4eab-b802-a4fcb4e0a198"}' 

Receiving: {"response":"200","objectList":[],"command":"SetCommand","messageID":"4edc3db9-7c98-4eab-b802-a4fcb4e0a198"}

Sending: '{"command":"GetQuery","queryName":"GetRemotes","arguments":"","messageID":"1ba401ea-5242-4385-b994-ff3819f9c66d"}'

Receiving: {"answer":[{"objnam":"R8F45","params":{"SUBTYP":"IS4","SNAME":"IS4 Remote 129","COMUART":"COMUART","MODULE":"MODULE","LISTORD":"129","BODY":"BODY","PUMP":"PUMP",**"ENABLE":"OFF"**,"MODE":"MODE","BUTTONS":[{"objnam":"bA21B","params":{"OBJNAM":"bA21B","LISTORD":"4","PARENT":"R8F45","CIRCUIT":"00000"}},{"objnam":"bDA73","params":{"OBJNAM":"bDA73","LISTORD":"3","PARENT":"R8F45","CIRCUIT":"00000"}},{"objnam":"b7EA6","params":{"OBJNAM":"b7EA6","LISTORD":"2","PARENT":"R8F45","CIRCUIT":"00000"}},{"objnam":"b6970","params":{"OBJNAM":"b6970","LISTORD":"1","PARENT":"R8F45","CIRCUIT":"00000"}}]}},{"objnam":"RAAF7","params":{"SUBTYP":"IS4","SNAME":"IS4 Remote 128","COMUART":"COMUART","MODULE":"MODULE","LISTORD":"128","BODY":"BODY","PUMP":"PUMP",**"ENABLE":"OFF"**,"MODE":"MODE","BUTTONS":[{"objnam":"b9BCA","params":{"OBJNAM":"b9BCA","LISTORD":"4","PARENT":"RAAF7","CIRCUIT":"00000"}},{"objnam":"b7F68","params":{"OBJNAM":"b7F68","LISTORD":"3","PARENT":"RAAF7","CIRCUIT":"00000"}},{"objnam":"b15FB","params":{"OBJNAM":"b15FB","LISTORD":"2","PARENT":"RAAF7","CIRCUIT":"00000"}},{"objnam":"b61C5","params":{"OBJNAM":"b61C5","LISTORD":"1","PARENT":"RAAF7","CIRCUIT":"00000"}}]}}],"command":"SendQuery","messageID":"1ba401ea-5242-4385-b994-ff3819f9c66d","response":"200"}

**Comment by klewis77** [comment]
Looks like it works in local mode but not remote. Do we have another server issue possibly?
Local Mode QA2
```json
//-----------------------------------------------------------
// TESTING ENABLE ON,OFF
// DEVICE     : OCP
// IPADDRESS  : 10.103.71.62  "QA2"
// OBJECT ID  : RAAF7 
// OBJECT TYPE: IS4
//-----------------------------------------------------------

//**** COMMAND: GET REMORES
{
 "command":"GetQuery",
 "queryName":"GetRemotes",
 "arguments":"",
 "messageID":"42343dfd-2d23-4c1c-be88-da7fc8b2050d"
}
//**** COMMAND: GET REMORES

{
    "command": "SendQuery",
    "messageID": "42343dfd-2d23-4c1c-be88-da7fc8b2050d",
    "queryName": "GetRemotes",
    "response": "200",
    "answer": [
        {
            "objnam": "R8F45",
            "params": {
                "SUBTYP": "IS4",
                "SNAME": "IS4 Remote 129",
                "COMUART": "COMUART",
                "MODULE": "MODULE",
                "LISTORD": "129",
                "BODY": "BODY",
                "PUMP": "PUMP",
                "ENABLE": "OFF",
                "MODE": "MODE",
                "BUTTONS": [
                    {
                        "objnam": "bA21B",
                        "params": {
                            "OBJNAM": "bA21B",
                            "LISTORD": "4",
                            "PARENT": "R8F45",
                            "CIRCUIT": "00000"
                        }
                    },
                    {
                        "objnam": "bDA73",
                        "params": {
                            "OBJNAM": "bDA73",
                            "LISTORD": "3",
                            "PARENT": "R8F45",
                            "CIRCUIT": "00000"
                        }
                    },
                    {
                        "objnam": "b7EA6",
                        "params": {
                            "OBJNAM": "b7EA6",
                            "LISTORD": "2",
                            "PARENT": "R8F45",
                            "CIRCUIT": "00000"
                        }
                    },
                    {
                        "objnam": "b6970",
                        "params": {
                            "OBJNAM": "b6970",
                            "LISTORD": "1",
                            "PARENT": "R8F45",
                            "CIRCUIT": "CB714"
                        }
                    }
                ]
            }
        },
        {
            "objnam": "RAAF7",
            "params": {
                "SUBTYP": "IS4",
                "SNAME": " SET IT TO ----OFF ON NAME",
                "COMUART": "COMUART",
                "MODULE": "MODULE",
                "LISTORD": "128",
                "BODY": "BODY",
                "PUMP": "PUMP",
                "ENABLE": "OFF",
                "MODE": "MODE",
                "BUTTONS": [
                    {
                        "objnam": "b9BCA",
                        "params": {
                            "OBJNAM": "b9BCA",
                            "LISTORD": "4",
                            "PARENT": "RAAF7",
                            "CIRCUIT": "00000"
                        }
                    },
                    {
                        "objnam": "b7F68",
                        "params": {
                            "OBJNAM": "b7F68",
                            "LISTORD": "3",
                            "PARENT": "RAAF7",
                            "CIRCUIT": "00000"
                        }
                    },
                    {
                        "objnam": "b15FB",
                        "params": {
                            "OBJNAM": "b15FB",
                            "LISTORD": "2",
                            "PARENT": "RAAF7",
                            "CIRCUIT": "00000"
                        }
                    },
                    {
                        "objnam": "b61C5",
                        "params": {
                            "OBJNAM": "b61C5",
                            "LISTORD": "1",
                            "PARENT": "RAAF7",
                            "CIRCUIT": "00000"
                        }
                    }
                ]
            }
        }
    ]
}

//**** COMMAND: EditRemote ENABLE ON IS4

{"command":"SetCommand",
"method":"EditRemote",
"arguments":[{
                "objnam":"RAAF7",
                "params":{"SNAME":"SET IT TO ----ON, AT FIELD NAME",
                "SUBTYP":"IS4",
                "ENABLE":"ON"
               }
          }],
"messageID":"a75a4672-b1c0-4b71-bac0-10ef3d1a3513"
} 

//**** REPLY: EditRemote ENABLE ON IS4

{
    "command": "SetCommand",
    "messageID": "a75a4672-b1c0-4b71-bac0-10ef3d1a3513",
    "method": "EditRemote",
    "response": "200",
    "answer": [
        {
            "objnam": "RAAF7",
            "params": {
                "SUBTYP": "IS4",
                "SNAME": "SET IT TO ----ON, AT FIELD NAME",
                "COMUART": "COMUART",
                "LISTORD": "128",
                "BODY": "BODY",
                "PUMP": "PUMP",
                "ENABLE": "ON",
                "MODE": "MODE",
                "BUTTONS": [
                    {
                        "objnam": "b9BCA",
                        "params": {
                            "LISTORD": "4",
                            "PARENT": "RAAF7",
                            "CIRCUIT": "00000"
                        }
                    },
                    {
                        "objnam": "b7F68",
                        "params": {
                            "LISTORD": "3",
                            "PARENT": "RAAF7",
                            "CIRCUIT": "00000"
                        }
                    },
                    {
                        "objnam": "b15FB",
                        "params": {
                            "LISTORD": "2",
                            "PARENT": "RAAF7",
                            "CIRCUIT": "00000"
                        }
                    },
                    {
                        "objnam": "b61C5",
                        "params": {
                            "LISTORD": "1",
                            "PARENT": "RAAF7",
                            "CIRCUIT": "00000"
                        }
                    }
                ]
            }
        }
    ]
}
{
    "command": "WriteParamList",
    "messageID": "70c36100-8e53-4e55-aa7e-4a982a4a539b",
    "timeSince": "1453664886",
    "timeNow": "1453664978",
    "objectList": [
        {
            "changes": [
                {
                    "objnam": "RAAF7",
                    "params": {
                        "SNAME": "SET IT TO ----ON, AT FIELD NAME",
                        "ENABLE": "ON"
                    }
                },
                {
                    "objnam": "_5451",
                    "params": {
                        "COUNT": "23"
                    }
                }
            ]
        }
    ]
}

//**** COMMAND: EditRemote ENABLE OFF IS4
{"command":"SetCommand",
"method":"EditRemote",
"arguments":[{
                "objnam":"RAAF7",
                "params":{"SNAME":"SET IT TO ----OFF, AT FIELD NAME",
                "SUBTYP":"IS4",
                "ENABLE":"OFF"
               }
          }],
"messageID":"a75a4672-b1c0-4b71-bac0-10ef3d1a3513"
} 

//**** REPLY: EditRemote ENABLE OFF IS4

{
    "command": "SetCommand",
    "messageID": "a75a4672-b1c0-4b71-bac0-10ef3d1a3513",
    "method": "EditRemote",
    "response": "200",
    "answer": [
        {
            "objnam": "RAAF7",
            "params": {
                "SUBTYP": "IS4",
                "SNAME": "SET IT TO ----OFF, AT FIELD NAME",
                "COMUART": "COMUART",
                "LISTORD": "128",
                "BODY": "BODY",
                "PUMP": "PUMP",
                "ENABLE": "OFF",
                "MODE": "MODE",
                "BUTTONS": [
                    {
                        "objnam": "b9BCA",
                        "params": {
                            "LISTORD": "4",
                            "PARENT": "RAAF7",
                            "CIRCUIT": "00000"
                        }
                    },
                    {
                        "objnam": "b7F68",
                        "params": {
                            "LISTORD": "3",
                            "PARENT": "RAAF7",
                            "CIRCUIT": "00000"
                        }
                    },
                    {
                        "objnam": "b15FB",
                        "params": {
                            "LISTORD": "2",
                            "PARENT": "RAAF7",
                            "CIRCUIT": "00000"
                        }
                    },
                    {
                        "objnam": "b61C5",
                        "params": {
                            "LISTORD": "1",
                            "PARENT": "RAAF7",
                            "CIRCUIT": "00000"
                        }
                    }
                ]
            }
        }
    ]
}
```

**Comment by acarnagey** [comment]
you didn’t run getRemotes after your editRemote calls, the getRemotes response is what is contradicting the editRemote response

**Comment by acarnagey** [comment]
On dev1, don't change both is4 enable toggles, just do one, and in the getRemotes you should see them both change:

Sending: '{"command":"SetCommand","method":"EditRemote","arguments":[{"objnam":"R5C82","params":{"SNAME":"IS4 Remote 128","SUBTYP":"IS4",**"ENABLE":"ON"**,"BUTTONS":[{"OBJNAM":"b4292","LISTORD":"1","CIRCUIT":"00000"},{"OBJNAM":"bAB0B","LISTORD":"2","CIRCUIT":"00000"},{"OBJNAM":"b8AFB","LISTORD":"3","CIRCUIT":"00000"},{"OBJNAM":"b0269","LISTORD":"4","CIRCUIT":"00000"}]}}],"messageID":"5d6c617e-65af-48bf-aa44-fc3705ceeeec"}'

Receiving: {"response":"200","objectList":[],"command":"SetCommand","messageID":"5d6c617e-65af-48bf-aa44-fc3705ceeeec"}

Sending: '{"command":"GetQuery","queryName":"GetRemotes","arguments":"","messageID":"d23b2fe7-0dae-4dce-9bed-19708571e69e"}' : Thu Jul 14 2016 10:37:59 GMT-0500 (CDT)
2016-07-14 10:37:59.385 SocketService.js:91 Receiving: {"answer":[{"objnam":"RA16A","params":{"SUBTYP":"IS4","SNAME":"IS4 Remote 129","COMUART":"COMUART","MODULE":"MODULE","LISTORD":"129","BODY":"BODY","PUMP":"PUMP",**"ENABLE":"ON"**,"MODE":"MODE","BUTTONS":[{"objnam":"b9F5E","params":{"OBJNAM":"b9F5E","LISTORD":"4","PARENT":"RA16A","CIRCUIT":"00000"}},{"objnam":"b3566","params":{"OBJNAM":"b3566","LISTORD":"3","PARENT":"RA16A","CIRCUIT":"00000"}},{"objnam":"b6F8C","params":{"OBJNAM":"b6F8C","LISTORD":"2","PARENT":"RA16A","CIRCUIT":"00000"}},{"objnam":"b0E2B","params":{"OBJNAM":"b0E2B","LISTORD":"1","PARENT":"RA16A","CIRCUIT":"00000"}}]}},{"objnam":"R5C82","params":{"SUBTYP":"IS4","SNAME":"IS4 Remote 128","COMUART":"COMUART","MODULE":"MODULE","LISTORD":"128","BODY":"BODY","PUMP":"PUMP",**"ENABLE":"ON"**,"MODE":"MODE","BUTTONS":[{"objnam":"b0269","params":{"OBJNAM":"b0269","LISTORD":"4","PARENT":"R5C82","CIRCUIT":"00000"}},{"objnam":"b8AFB","params":{"OBJNAM":"b8AFB","LISTORD":"3","PARENT":"R5C82","CIRCUIT":"00000"}},{"objnam":"bAB0B","params":{"OBJNAM":"bAB0B","LISTORD":"2","PARENT":"R5C82","CIRCUIT":"00000"}},{"objnam":"b4292","params":{"OBJNAM":"b4292","LISTORD":"1","PARENT":"R5C82","CIRCUIT":"00000"}}]}}],"queryName":"GetRemotes","command":"SendQuery","messageID":"d23b2fe7-0dae-4dce-9bed-19708571e69e","response":"200"}

Sending: '{"command":"SetCommand","method":"EditRemote","arguments":[{"objnam":"R5C82","params":{"SNAME":"IS4 Remote 128","SUBTYP":"IS4",**"ENABLE":"OFF"**,"BUTTONS":[{"OBJNAM":"b4292","LISTORD":"1","CIRCUIT":"00000"},{"OBJNAM":"bAB0B","LISTORD":"2","CIRCUIT":"00000"},{"OBJNAM":"b8AFB","LISTORD":"3","CIRCUIT":"00000"},{"OBJNAM":"b0269","LISTORD":"4","CIRCUIT":"00000"}]}}],"messageID":"2493ac4a-7308-45b3-a300-d6376be44aa2"}'

Receiving: {"response":"200","objectList":[],"command":"SetCommand","messageID":"2493ac4a-7308-45b3-a300-d6376be44aa2"}

Sending: '{"command":"GetQuery","queryName":"GetRemotes","arguments":"","messageID":"a861227b-6944-4407-b4eb-6613b6a939b9"}' 

Receiving: {"answer":[{"objnam":"RA16A","params":{"SUBTYP":"IS4","SNAME":"IS4 Remote 129","COMUART":"COMUART","MODULE":"MODULE","LISTORD":"129","BODY":"BODY","PUMP":"PUMP",**"ENABLE":"OFF"**,"MODE":"MODE","BUTTONS":[{"objnam":"b9F5E","params":{"OBJNAM":"b9F5E","LISTORD":"4","PARENT":"RA16A","CIRCUIT":"00000"}},{"objnam":"b3566","params":{"OBJNAM":"b3566","LISTORD":"3","PARENT":"RA16A","CIRCUIT":"00000"}},{"objnam":"b6F8C","params":{"OBJNAM":"b6F8C","LISTORD":"2","PARENT":"RA16A","CIRCUIT":"00000"}},{"objnam":"b0E2B","params":{"OBJNAM":"b0E2B","LISTORD":"1","PARENT":"RA16A","CIRCUIT":"00000"}}]}},{"objnam":"R5C82","params":{"SUBTYP":"IS4","SNAME":"IS4 Remote 128","COMUART":"COMUART","MODULE":"MODULE","LISTORD":"128","BODY":"BODY","PUMP":"PUMP",**"ENABLE":"OFF"**,"MODE":"MODE","BUTTONS":[{"objnam":"b0269","params":{"OBJNAM":"b0269","LISTORD":"4","PARENT":"R5C82","CIRCUIT":"00000"}},{"objnam":"b8AFB","params":{"OBJNAM":"b8AFB","LISTORD":"3","PARENT":"R5C82","CIRCUIT":"00000"}},{"objnam":"bAB0B","params":{"OBJNAM":"bAB0B","LISTORD":"2","PARENT":"R5C82","CIRCUIT":"00000"}},{"objnam":"b4292","params":{"OBJNAM":"b4292","LISTORD":"1","PARENT":"R5C82","CIRCUIT":"00000"}}]}}],"queryName":"GetRemotes","command":"SendQuery","messageID":"a861227b-6944-4407-b4eb-6613b6a939b9","response":"200"}

**Comment by klewis77** [comment]
@acarnagey  I thought we fixed this using SetParamList?

**Comment by klewis77** [comment]
This needs to be verified using the SetParamList per conversation on slack

**Comment by acarnagey** [comment]
@klewis77 we decided to use SetParamList for EditObjectAffect, not EditRemote.  As far as I know we were going to use EditRemote here.  Earlier in the conversation you were asking me to try using SetParamList instead, I tied it and it had the same outcome, the other remotes enable field were getting set as well.

**Comment by klewis77** [comment]
you can do exactly the same things with SetParamList that you are doing in EditRemote

**Comment by acarnagey** [comment]
setparamlist is having the same issue where it sets other remotes enabled too.

**Comment by acarnagey** [comment]
verified on dev1
<img width="1901" alt="screen shot 2016-07-19 at 12 58 15 pm" src="https://cloud.githubusercontent.com/assets/1028600/16960825/9c98f95e-4db0-11e6-9a56-de5826b51307.png">
