### ISSUE TITLE
Address update issue

### ISSUE THREAD

**Issue by acarnagey** [gryz/THW-Update-Needed#17]
THW notifyList returns 404 when attempting to update address directly to THW.

Might be an issue with the city properly updating but I wasn't able to replicate from QA.

{"objectList":[{"objnam":"_5451","params":{"ADDRESS":"456 Avienda Gaviota","CITY":"Camarillo","STATE":" CA","ZIP":"93012","COUNTRY":"United States","TIMZON":"-8","DLSTIM":"ON"}}],"command":"SETPARAMLIST","messageID":"b71f5bb1-e1f7-4474-a02f-258b1376c241:d6e0216b-ad55-e611-82eb-8fd78b1767ed","response":null} 

{"command": "NotifyList","messageID": "b71f5bb1-e1f7-4474-a02f-258b1376c241:d6e0216b-ad55-e611-82eb-8fd78b1767ed","response": "404"} {"command": "WriteParamList","messageID": "798d470c-2157-497f-9e45-fa7ff492724d","timeSince": "0","timeNow": "1469808374", "objectList": [{} ]}

**Comment by klewis77** [comment]
DLSTIM is not part of the _5451 object is why you get a 404 error

**Comment by acarnagey** [comment]
Thanks, this is fixed, moved it to _C10C
