### ISSUE TITLE
PEN-1100.12 - As a pool owner/user I need to be able to view all notifications. (strange text)

### ISSUE THREAD

**Issue by acarnagey** [gryz/THW-Update-Needed#24]
On QA 1 we are getting a notification with strange text, the SNAME's %RPM %etc:

{"answer":[{"objnam":"t3474","params":{"OBJTYP":"STATUS","PARENT":"P3A97","MODE":"2","SNAME":"%RPM RPM,  %PWR Watts","COUNT":"0","PARTY":"","SINDEX":"54924","TIME":"0","SHOMNU":"ON"}},{"objnam":"t1492","params":{"OBJTYP":"STATUS","PARENT":"PC795","MODE":"2","SNAME":"%RPM RPM, %GPM GPM,  %PWR Watts","COUNT":"0","PARTY":"","SINDEX":"54924","TIME":"0","SHOMNU":"ON"}}],"queryName":"GetActiveStatusMessages","command":"SendQuery","messageID":"80a822a4-6fdc-4b23-b4fe-cd6139b838e3","response":"200"}

related to https://bitbucket.org/pathf/pentair-issues/issues/279/notification-with-strange-text-possibly-a

**Comment by klewis77** [comment]
Yeah that is intentional. The %RPM is the string place holder for the RPM value of the parent pump. The paradigm is that the parameter after the % is the token to request for the parent item. So in this case we would do a request of the RPM from the pump object

**Comment by acarnagey** [comment]
ok makes sense, will work on this one to get it to scan the string and split by white space, find any words that begin with ‘%’ and swap out the word for the parent object’s attribute if it is there.
