### ISSUE TITLE
Attempting to delete a VS pump causes the THW connection to crash

### ISSUE THREAD

**Issue by acarnagey** [gryz/THW-Update-Needed#25]
tested on qa2.
Sending: '{"command":"SetCommand","method":"DeleteObject","arguments":["P6A71"],"messageID":"d0719ce8-6266-48cc-82f6-cbdaf17a222d"}' : Tue Aug 09 2016 12:06:23 GMT-0500 (CDT)
SocketService.js:79 Connection Terminated : Tue Aug 09 2016 12:06:23 GMT-0500 (CDT)
SocketService.js:75 WebSocket connection to 'wss://pentqa.pathf.com/service//api/websocket/11?access-token=nd_JSfxD-XsAh…8GQZm9S0CDOOy4kSU3BRmdk1WWdo39Ip_fqvXVVX4iLPce30_DTDoBFWfUORhFu3Nlcf8s5FlI' failed: Error during WebSocket handshake: Unexpected response code: 503newSocket @ SocketService.js:75connectToProperty @ PropertyService.js:954factory.Connect @ PropertyService.js:439(anonymous function) @ PropertyService.js:1057(anonymous function) @ angular.js:17782completeOutstandingRequest @ angular.js:5490(anonymous function) @ angular.js:5762
SocketService.js:83 Error: Tue Aug 09 2016 12:06:24 GMT-0500 (CDT) ---undefined

**Comment by edgardoatpentair** [comment]
has been fixed I pushed the code already .
check test below.

1 [COMMAND ] : CREATE OBJECT PUMP

{"command":"CREATEOBJECT",
  "objectList":[{"objtyp":"PUMP","params":                  {"SNAME":"vs8","SUBTYP":"SPEED","PRIMFLO":"400","PRIMTIM":"0","COMUART":"undefined","MIN":"400","MAX":"400","PRIOR":"CUSTOM","SETTMP":"10"}}],"messageID":"0905e29c-d2dc-491f-a85a-df6a527da4d2"}

1 -[REPLY] :  RESPONSE
{
    "command": "ObjectCreated",
    "messageID": "0905e29c-d2dc-491f-a85a-df6a527da4d2",
    "objnam": "P30AD",
    "response": "201"
}
----------------------------------------
2- [COMMAND] : DESTROY OBJECT FROM ABOVE COMMAND "P30AD"
{"command":"SetCommand",
   "method":"DeleteObject",
   "arguments":["P30AD"],
   "messageID":"d0719ce8-6266-48cc-82f6-cbdaf17a222d"}

2- [REPLY] : 

{
    "command": "SetCommand",
    "messageID": "d0719ce8-6266-48cc-82f6-cbdaf17a222d",
    "method": "DeleteObject",
    "response": "200"
}
