### ISSUE TITLE
PEN-1000.2.2 As a pool owner/user I need to be able to reconfigure circuit groups/macro installation so I can manage my pool/spa. [2]

### ISSUE THREAD

**Issue by acarnagey** [gryz/THW-Update-Needed#26]
Currently the EditGroup call will delete all existing circuitAffects and create new circuitAffects.  We had decided to make the edit call to check whether the system would need to add/edit/or delete a circuitAffect accordingly to preserve the existing circuitAffects that might have only been edited.

**Comment by klewis77** [comment]
This should be working as intended. This was fixed some time ago
