### ISSUE TITLE
PEN-1000.3.9 As a pool owner/user I need to be able to configure and reconfigure standard valves within the installation, so I can manage my pool/spa.

### ISSUE THREAD

**Issue by sevennote** [gryz/THW-Update-Needed#5]
https://pathfinder.atlassian.net/wiki/x/-oDuBQ

With an hname of intake or return, can't change the circuit. If solar is present would consume valve a and circuit would not be changeable. Otherwise Valve could up to A - G if have a valve expansion, or if have a valve expansion panel, could have more.
adam[ 12:23 PM ] 
@klewis03: we noticed that the THW response for object affects for creating and editing was off.
For example the .net server gets
```
{
    "command": "CreateObjectAffect",
    "messageID": ":d84948aa-d475-4e71-bf65-70d45ceac59c",
    "response": "200",
    "objectList": [ ...
```
where the response is supposed to be like https://pathfinder.atlassian.net/wiki/display/PEN/Create+Object+Affect
```
{
    "command": "SetCommand", 
    "messageID": "10A86ef1-88f1-8091-7cdf2b", 
    "method": "CreateObjectAffect", 
    "response": "200", 
    "objectList": [ ...
```
command needs to be SetCommand and method needs to be CreateObjectAffect or EditObjectAffect basically.  Thats why we weren’t getting a response back from the .net server. (edited)
klewis03[ 12:52 PM ] 
so when you do the request in the new way it works?
[ 12:53 ] 
thats a good catch
In order to get by OCP, can get info in multiple calls, would it be better/worth it to do it as a API call? with the new getHardwareDefinition() (that is what we ended up doing !)

**Comment by acarnagey** [comment]
Functionally this does what it should, but the response format is off so I had to confirm that it is still off based on the API documentation specs, with the response format off, the .net server doesn’t return a response so the web client never gets a response.
