### ISSUE TITLE
PEN-1000.4.1e As a pool owner/user I need to be able to add/remove/configure Two Speed pumps within the installation so I can add/assign/remove circuits connected with pump.

### ISSUE THREAD

**Issue by sevennote** [gryz/THW-Update-Needed#6]
https://pathfinder.atlassian.net/wiki/pages/viewpage.action?pageId=109117448

adam[ 12:23 PM ] 
@klewis03: we noticed that the THW response for object affects for creating and editing was off.
For example the .net server gets
```
{
    "command": "CreateObjectAffect",
    "messageID": ":d84948aa-d475-4e71-bf65-70d45ceac59c",
    "response": "200",
    "objectList": [ ...
```
where the response is supposed to be like https://pathfinder.atlassian.net/wiki/display/PEN/Create+Object+Affect
```
{
    "command": "SetCommand", 
    "messageID": "10A86ef1-88f1-8091-7cdf2b", 
    "method": "CreateObjectAffect", 
    "response": "200", 
    "objectList": [ ...
```
command needs to be SetCommand and method needs to be CreateObjectAffect or EditObjectAffect basically.  Thats why we weren’t getting a response back from the .net server. (edited)
klewis03[ 12:52 PM ] 
so when you do the request in the new way it works?
[ 12:53 ] 
thats a good catch

**Comment by gryz** [comment]
Asked to check if working by Keith.

**Comment by acarnagey** [comment]
Functionally this does what it should, but the response format is off so I had to confirm that it is still off based on the API documentation specs, with the response format off, the .net server doesn’t return a response so the web client never gets a response.
