### ISSUE TITLE
PEN-1000.3.5 As a pool owner/user I need to be able to configure and reconfigure heaters within the installation, so I can manage my pool/spa.

### ISSUE THREAD

**Issue by sevennote** [gryz/THW-Update-Needed#7]
https://pathfinder.atlassian.net/wiki/x/MgCeBQ

6/6/2016 - getting the shared body from the heater
So the shared body needs to be linked to the heater object somehow, for instance in this request / response the object name  HCB73 share parameter does not exist for the get configuration call, it would be preferrable that it exists here, but we also can't get it from RequestParamList as it shows up as SHARE: SHARE, also noted in the reponse below:
Calls are from UAT 1
Get Configuration Request
{"command":"GetQuery", "queryName":"GetConfiguration", "arguments":"", "messageID":"31d161bc-5076-447d-b898-05ca61bb48d0"}
Get Configuration Response
{"answer":
  [ ...
 "OBJLIST": [{
        "objnam": "HCB73",
 "params": {"OBJTYP": "HEATER", "SUBTYP": "ULTRA", "SNAME": "Pool/Spa UltraTemp"}
      ... 
  }], "command":"SendQuery", "messageID":"b6125f8b-9d27-4833-8193-6cd24ef6ae3e", "response":"200"
}
Request Param List request:
{"command":"RequestParamList","objectList":[{"objnam":"UFFFE","keys":["ENABLE","OBJTYP","PASSWRD","SHOMNU"]},{"objnam":"C3A29","keys":["STATUS","MODE","LISTORD","USAGE","ACT","FREEZE","LIMIT","USE","MANUAL","FEATR","DNTSTP","CHILD","HNAME","SNAME","OBJNAM","OBJTYP","SHOMNU","TIME","TIMOUT","SOURCE","SUBTYP"]},{"objnam":"C8CDD","keys":["STATUS","MODE","LISTORD","USAGE","ACT","FREEZE","LIMIT","USE","MANUAL","FEATR","DNTSTP","CHILD","HNAME","SNAME","OBJNAM","OBJTYP","SHOMNU","TIME","TIMOUT","SOURCE","SUBTYP","LIMIT"]},{"objnam":"C2A52","keys":["STATUS","MODE","LISTORD","USAGE","ACT","FREEZE","LIMIT","USE","MANUAL","FEATR","DNTSTP","CHILD","HNAME","SNAME","OBJNAM","OBJTYP","SHOMNU","TIME","TIMOUT","SOURCE","SUBTYP","LIMIT"]},{"objnam":"CE7C0","keys":["STATUS","MODE","LISTORD","USAGE","ACT","FREEZE","LIMIT","USE","MANUAL","FEATR","DNTSTP","CHILD","HNAME","SNAME","OBJNAM","OBJTYP","SHOMNU","TIME","TIMOUT","SOURCE","SUBTYP"]},{"objnam":"C4794","keys":["STATUS","MODE","LISTORD","USAGE","ACT","FREEZE","LIMIT","USE","MANUAL","FEATR","DNTSTP","CHILD","HNAME","SNAME","OBJNAM","OBJTYP","SHOMNU","TIME","TIMOUT","SOURCE","SUBTYP"]},{"objnam":"C3A29","keys":["STATUS","MODE","LISTORD","USAGE","ACT","FREEZE","LIMIT","USE","MANUAL","FEATR","DNTSTP","CHILD","HNAME","SNAME","OBJNAM","OBJTYP","SHOMNU","TIME","TIMOUT","SOURCE","SUBTYP"]},{"objnam":"C8CDD","keys":["STATUS","MODE","LISTORD","USAGE","ACT","FREEZE","LIMIT","USE","MANUAL","FEATR","DNTSTP","CHILD","HNAME","SNAME","OBJNAM","OBJTYP","SHOMNU","TIME","TIMOUT","SOURCE","SUBTYP","LIMIT"]},{"objnam":"CFD43","keys":["STATUS","MODE","LISTORD","USAGE","ACT","FREEZE","LIMIT","USE","MANUAL","FEATR","DNTSTP","CHILD","HNAME","SNAME","OBJNAM","OBJTYP","SHOMNU","TIME","TIMOUT","SOURCE","SUBTYP"]},{"objnam":"C2A52","keys":["STATUS","MODE","LISTORD","USAGE","ACT","FREEZE","LIMIT","USE","MANUAL","FEATR","DNTSTP","CHILD","HNAME","SNAME","OBJNAM","OBJTYP","SHOMNU","TIME","TIMOUT","SOURCE","SUBTYP","LIMIT"]},{"objnam":"CE7C0","keys":["STATUS","MODE","LISTORD","USAGE","ACT","FREEZE","LIMIT","USE","MANUAL","FEATR","DNTSTP","CHILD","HNAME","SNAME","OBJNAM","OBJTYP","SHOMNU","TIME","TIMOUT","SOURCE","SUBTYP"]},{"objnam":"CA06A","keys":["STATUS","MODE","LISTORD","USAGE","ACT","FREEZE","LIMIT","USE","MANUAL","FEATR","DNTSTP","CHILD","HNAME","SNAME","OBJNAM","OBJTYP","SHOMNU","TIME","TIMOUT","SOURCE","SUBTYP"]},{"objnam":"C4794","keys":["STATUS","MODE","LISTORD","USAGE","ACT","FREEZE","LIMIT","USE","MANUAL","FEATR","DNTSTP","CHILD","HNAME","SNAME","OBJNAM","OBJTYP","SHOMNU","TIME","TIMOUT","SOURCE","SUBTYP"]},{"objnam":"C88CE","keys":["STATUS","MODE","LISTORD","USAGE","ACT","FREEZE","LIMIT","USE","MANUAL","FEATR","DNTSTP","CHILD","HNAME","SNAME","OBJNAM","OBJTYP","SHOMNU","TIME","TIMOUT","SOURCE","SUBTYP"]},{"objnam":"_5451","keys":["OBJTYP","MODE","AVAIL","TEMPNC","VACFLO","VACTIM","START","STOP"]},{"objnam":"_A135","keys":["OBJTYP","SUBTYP","PROBE","STATUS"]},{"objnam":"B611A","keys":["TEMP","HITMP","LOTMP","HEATER","STATUS","HTSRC","VOL","MANUAL","LSTTMP","HNAME"]},{"objnam":"B7CA9","keys":["TEMP","HITMP","LOTMP","HEATER","STATUS","HTSRC","VOL","MANUAL","LSTTMP","HNAME"]},{"objnam":"HCB73","keys":["STATUS","SUBTYP","PERMIT","TIMOUT","READY","HTMODE","SHOMNU","COOL","COMUART","BODY","SHARE","HNAME","START","STOP","HEATING","SHARED"]},{"objnam":"HB162","keys":["STATUS","SUBTYP","PERMIT","TIMOUT","READY","HTMODE","SHOMNU","COOL","COMUART","BODY","SHARE","HNAME","START","STOP","HEATING","SHARED"]},{"objnam":"H41E8","keys":["STATUS","SUBTYP","PERMIT","TIMOUT","READY","HTMODE","SHOMNU","COOL","COMUART","BODY","SHARE","HNAME","START","STOP","HEATING","SHARED"]},{"objnam":"H1C2E","keys":["STATUS","SUBTYP","PERMIT","TIMOUT","READY","HTMODE","SHOMNU","COOL","COMUART","BODY","SHARE","HNAME","START","STOP","HEATING","SHARED"]},{"objnam":"I86C6","keys":["PHSET","ORPSET","PHTNK","ORPTNK","CALC","CYACID","ALK","SALT","ORPVAL","PHVAL","SINDEX","PHLO","PHHI","ORPLO","ORPHI"]},{"objnam":"I4ACB","keys":["SALT","PRIM","SEC","SUPER","TIMOUT"]},{"objnam":"R8282","keys":["ENABLE"]},{"objnam":"RFC45","keys":["ENABLE"]},{"objnam":"I86C6","keys":["PHSET","ORPSET","PHTNK","ORPTNK","CALC","CYACID","ALK","SALT","ORPVAL","PHVAL","SINDEX","PHLO","PHHI","ORPLO","ORPHI"]},{"objnam":"I4ACB","keys":["SALT","PRIM","SEC","SUPER","TIMOUT"]}],"messageID":"cbaca5c9-e411-4264-9805-12566a628c0d"
Request Param List response:
{"objectList":[ ... {"objnam":"HCB73","params":{"STATUS":"OFF","SUBTYP":"ULTRA","PERMIT":"PERMIT","TIMOUT":"TIMOUT","READY":"READY","HTMODE":"ULTRA","SHOMNU":"hcr","COOL":"ON","COMUART":"2097268","BODY":"B7CA9","SHARE":"SHARE","HNAME":"Pool/Spa UltraTemp","START":"2","STOP":"0","HEATING":"OFF","SHARED":""}}, ... ],"command":"NotifyList","messageID":"cbaca5c9-e411-4264-9805-12566a628c0d","response":"200","timeNow":3591325563,"timeSince":3591325559}
Per Keith he will have the developers look into it, ref group chat at 4:06.

**Comment by gryz** [comment]
Keith,

Was this ever fixed? It's been broken since May and we reviewed it June according to the notes on Confluence

**Comment by klewis77** [comment]
This should have been fixed

**Comment by acarnagey** [comment]
This has same issue on dev 1
{"command":"RequestParamList","objectList":[{"objnam":"H7B00","keys":["STATUS","SUBTYP","PERMIT","TIMOUT","READY","HTMODE","SHOMNU","COOL","COMUART","BODY","SHARE","HNAME","START","STOP","HEATING","SHARED","SHARE"]}],"messageID":"99b45c7a-43a3-4621-aae1-a847451c89d6"}

{"objectList":[{"objnam":"H7B00","params":{"STATUS":"OFF","SUBTYP":"GENERIC","PERMIT":"PERMIT","TIMOUT":"0","READY":"READY","HTMODE":"GENERIC","SHOMNU":"had","COOL":"OFF","COMUART":"COMUART","BODY":"B09E6","SHARE":"SHARE","HNAME":"Gas Heater 1","START":"0","STOP":"0","HEATING":"OFF","SHARED":""}}],"command":"NotifyList","messageID":"99b45c7a-43a3-4621-aae1-a847451c89d6","response":"200","timeNow":"946696288","timeSince":"946696269"}

It should say SHARE:"B66AC" as the shared body to pool is spa on DEV 1.

**Comment by gryz** [comment]
Keith,

You are verifying that this is still broke?

**Comment by klewis77** [comment]
I am looking into it now

**Comment by klewis77** [comment]
@acarnagey it does not appear that the SHARE parameter was implemented in the heater object. that would explain why you are receiving the response you see. There is a BODY parameter which will tell the body it is currently associated with.

What is the SHARE parameter being used for on the web app side?

**Comment by acarnagey** [comment]
Based off of the wireframe for heaters at https://pathfinder.atlassian.net/wiki/display/PEN/PEN-1000.3+Other+Equipment+Configuration+Screen on each form for the heater the body form control has a drop down for assigning a body to a heater, but it would display body, share. e.g. Pool, Spa

**Comment by klewis77** [comment]
The body drop down will show all available bodies (which is already obtained from GetHArdwareDefinition) not the SHARE parameter. The SHARE parameter only indicates that the body is shared (shared Equipment) with another and that is not always the case.

**Comment by klewis77** [comment]
The list of bodies in the heaters does not need to contain shared bodies. THW does not work in this way. You select a single body only for heaters

**Comment by acarnagey** [comment]
Removed shared and just show Body now for heater.
