### ISSUE TITLE
PEN-1000.2.2 As a pool owner/user I need to be able to (re) configure circuit groups/macro installation so I can manage my pool/spa.

### ISSUE THREAD

**Issue by sevennote** [gryz/THW-Update-Needed#9]
https://pathfinder.atlassian.net/wiki/x/QABgB

6/15/2016 can't update act to off, tested on qa1:
Sending: '{"command":"SetCommand","method":"EditGroup","arguments":{"OBJNAM":"C9E59","SNAME":"East Wing Romance!","OBJLIST":[{"objnam":"C508C","params":{"ACT":"OFF","LISTORD":1}},{"objnam":"C0A9E","params":{"ACT":"ON","LISTORD":2}}]},"messageID":"4a6a2743-332f-4174-8b66-f3a25f0dd8e4"}' 
Receiving: {"response":"200","objectList":[{"objnam":"C9E59","params":{"OBJTYP":"CIRCUIT","SUBTYP":"CIRCGRP","SNAME":"East Wing Romance!","LISTORD":"8","SHOMNU":"fcrehzmtow","USAGE":"D","COUNT":"2","OBJLIST":[{"objnam":"cC984","params":{"OBJTYP":"CIRCGRP","PARENT":"C9E59","CIRCUIT":"C508C","ACT":"OFF","DLY":"0","LISTORD":"1"}},{"objnam":"c487A","params":{"OBJTYP":"CIRCGRP","PARENT":"C9E59","CIRCUIT":"C0A9E","ACT":"ON","DLY":"0","LISTORD":"2"}}]}}],"command":"SetCommand","messageID":"4a6a2743-332f-4174-8b66-f3a25f0dd8e4"}
Sending: '{"command":"GetQuery","queryName":"GetHardwareDefinition","arguments":"","messageID":"88106362-7d7c-4d0e-a2d6-7dbec0753579"}'
Receiving: {"answer":[ … {"objnam": "C9E59","params": {"OBJTYP": "CIRCUIT","SUBTYP": "CIRCGRP","HNAME": "Circ Group 1","SNAME": "East Wing Romance!", "LISTORD": "8","PARENT": "00000","BODY": "00000","FREEZE": "OFF","VER": "VER","TIMZON": "TIMZON","TIME": "720","RLY": "RLY","DNTSTP": "OFF","FEATR": "ON","OBJLIST": [{"objnam": "cC984","params": {"OBJTYP": "CIRCGRP","CIRCUIT": "C508C", "ACT": "ON", "LISTORD": "1","DLY": "0"} } ...

**Comment by klewis77** [comment]
Off is not a valid ACT value. Please see the dataspec for clarificaiton

**Comment by acarnagey** [comment]
On the wireframe there is a toggle for turning on or off a circuit that's in a circuit group.  On the dataspec for circuit, affect ACT can be ON, OFF, or Light Action.  Currently couldn't set it to OFF.

**Comment by klewis77** [comment]
ACT is for the color/show of a light circuit. STATUS is to turn on off the circuit

**Comment by klewis77** [comment]
For a circuit affect you should be able to set ACT to ON or OFF but not the circuit itself

**Comment by acarnagey** [comment]
That's the thing, I can't set the circuit affect ACT to OFF.  It always sticks to ON in the getHardwareDefinition call. Just confirmed again on DEV1.  The response is correct but when the getHardwareDefinition gets called later it still says ON.

Sending: '{"command":"SetCommand","method":"EditGroup","arguments":{"OBJNAM":"CBE78","SNAME":"tjRb","OBJLIST":[{"objnam":"C705E","params":{"ACT":"OFF","LISTORD":1}},{"objnam":"CF28B","params":{"ACT":"OFF","LISTORD":1}}]},"messageID":"e35bb10a-fcc3-4fde-954a-6efacf95bf2a"}

{"response":"200","objectList":[{"objnam":"CBE78","params":{"OBJTYP":"CIRCUIT","SUBTYP":"CIRCGRP","SNAME":"tjRb","LISTORD":"11","SHOMNU":"fcrehzmtow","COUNT":"2","OBJLIST":[{"objnam":"c1A43","params":{"OBJTYP":"CIRCGRP","PARENT":"CBE78","CIRCUIT":"C705E","ACT":"OFF","DLY":"0","LISTORD":"1"}},{"objnam":"c4188","params":{"OBJTYP":"CIRCGRP","PARENT":"CBE78","CIRCUIT":"CF28B","ACT":"OFF","DLY":"0","LISTORD":"2"}}]}}],"command":"SetCommand","messageID":"e35bb10a-fcc3-4fde-954a-6efacf95bf2a"}

Sending: '{"command":"GetQuery","queryName":"GetHardwareDefinition","arguments":"","messageID":"c8983ad4-4279-4c8a-b8f8-520ba95ce33c"}'

Receiving: {"answer":[{"objnam":"M0000","params":{...{"objnam":"CBE78","params":{"OBJTYP":"CIRCUIT","SUBTYP":"CIRCGRP","HNAME":"Circ Group 1","SNAME":"tjRb","LISTORD":"11","PARENT":"00000","BODY":"00000","FREEZE":"OFF","VER":"VER","TIMZON":"TIMZON","TIME":"720","RLY":"RLY","DNTSTP":"OFF","FEATR":"ON","OBJLIST":[{"objnam":"c1A43","params":{"OBJTYP":"CIRCGRP","CIRCUIT":"C705E","ACT":"ON","LISTORD":"1","DLY":"0"}},{"objnam":"c4188","params":{"OBJTYP":"CIRCGRP","CIRCUIT":"CF28B","ACT":"ON","LISTORD":"2","DLY":"0"}}]}}...

**Comment by acarnagey** [comment]
On dev1, don't change both is4 enable toggles, just do one, and in the getRemotes you should see them both change:

Sending: '{"command":"SetCommand","method":"EditRemote","arguments":[{"objnam":"R5C82","params":{"SNAME":"IS4 Remote 128","SUBTYP":"IS4",**"ENABLE":"ON"**,"BUTTONS":[{"OBJNAM":"b4292","LISTORD":"1","CIRCUIT":"00000"},{"OBJNAM":"bAB0B","LISTORD":"2","CIRCUIT":"00000"},{"OBJNAM":"b8AFB","LISTORD":"3","CIRCUIT":"00000"},{"OBJNAM":"b0269","LISTORD":"4","CIRCUIT":"00000"}]}}],"messageID":"5d6c617e-65af-48bf-aa44-fc3705ceeeec"}'

Receiving: {"response":"200","objectList":[],"command":"SetCommand","messageID":"5d6c617e-65af-48bf-aa44-fc3705ceeeec"}

Sending: '{"command":"GetQuery","queryName":"GetRemotes","arguments":"","messageID":"d23b2fe7-0dae-4dce-9bed-19708571e69e"}' : Thu Jul 14 2016 10:37:59 GMT-0500 (CDT)
2016-07-14 10:37:59.385 SocketService.js:91 Receiving: {"answer":[{"objnam":"RA16A","params":{"SUBTYP":"IS4","SNAME":"IS4 Remote 129","COMUART":"COMUART","MODULE":"MODULE","LISTORD":"129","BODY":"BODY","PUMP":"PUMP",**"ENABLE":"ON"**,"MODE":"MODE","BUTTONS":[{"objnam":"b9F5E","params":{"OBJNAM":"b9F5E","LISTORD":"4","PARENT":"RA16A","CIRCUIT":"00000"}},{"objnam":"b3566","params":{"OBJNAM":"b3566","LISTORD":"3","PARENT":"RA16A","CIRCUIT":"00000"}},{"objnam":"b6F8C","params":{"OBJNAM":"b6F8C","LISTORD":"2","PARENT":"RA16A","CIRCUIT":"00000"}},{"objnam":"b0E2B","params":{"OBJNAM":"b0E2B","LISTORD":"1","PARENT":"RA16A","CIRCUIT":"00000"}}]}},{"objnam":"R5C82","params":{"SUBTYP":"IS4","SNAME":"IS4 Remote 128","COMUART":"COMUART","MODULE":"MODULE","LISTORD":"128","BODY":"BODY","PUMP":"PUMP",**"ENABLE":"ON"**,"MODE":"MODE","BUTTONS":[{"objnam":"b0269","params":{"OBJNAM":"b0269","LISTORD":"4","PARENT":"R5C82","CIRCUIT":"00000"}},{"objnam":"b8AFB","params":{"OBJNAM":"b8AFB","LISTORD":"3","PARENT":"R5C82","CIRCUIT":"00000"}},{"objnam":"bAB0B","params":{"OBJNAM":"bAB0B","LISTORD":"2","PARENT":"R5C82","CIRCUIT":"00000"}},{"objnam":"b4292","params":{"OBJNAM":"b4292","LISTORD":"1","PARENT":"R5C82","CIRCUIT":"00000"}}]}}],"queryName":"GetRemotes","command":"SendQuery","messageID":"d23b2fe7-0dae-4dce-9bed-19708571e69e","response":"200"}

Sending: '{"command":"SetCommand","method":"EditRemote","arguments":[{"objnam":"R5C82","params":{"SNAME":"IS4 Remote 128","SUBTYP":"IS4",**"ENABLE":"OFF"**,"BUTTONS":[{"OBJNAM":"b4292","LISTORD":"1","CIRCUIT":"00000"},{"OBJNAM":"bAB0B","LISTORD":"2","CIRCUIT":"00000"},{"OBJNAM":"b8AFB","LISTORD":"3","CIRCUIT":"00000"},{"OBJNAM":"b0269","LISTORD":"4","CIRCUIT":"00000"}]}}],"messageID":"2493ac4a-7308-45b3-a300-d6376be44aa2"}'

Receiving: {"response":"200","objectList":[],"command":"SetCommand","messageID":"2493ac4a-7308-45b3-a300-d6376be44aa2"}

Sending: '{"command":"GetQuery","queryName":"GetRemotes","arguments":"","messageID":"a861227b-6944-4407-b4eb-6613b6a939b9"}' 

Receiving: {"answer":[{"objnam":"RA16A","params":{"SUBTYP":"IS4","SNAME":"IS4 Remote 129","COMUART":"COMUART","MODULE":"MODULE","LISTORD":"129","BODY":"BODY","PUMP":"PUMP",**"ENABLE":"OFF"**,"MODE":"MODE","BUTTONS":[{"objnam":"b9F5E","params":{"OBJNAM":"b9F5E","LISTORD":"4","PARENT":"RA16A","CIRCUIT":"00000"}},{"objnam":"b3566","params":{"OBJNAM":"b3566","LISTORD":"3","PARENT":"RA16A","CIRCUIT":"00000"}},{"objnam":"b6F8C","params":{"OBJNAM":"b6F8C","LISTORD":"2","PARENT":"RA16A","CIRCUIT":"00000"}},{"objnam":"b0E2B","params":{"OBJNAM":"b0E2B","LISTORD":"1","PARENT":"RA16A","CIRCUIT":"00000"}}]}},{"objnam":"R5C82","params":{"SUBTYP":"IS4","SNAME":"IS4 Remote 128","COMUART":"COMUART","MODULE":"MODULE","LISTORD":"128","BODY":"BODY","PUMP":"PUMP",**"ENABLE":"OFF"**,"MODE":"MODE","BUTTONS":[{"objnam":"b0269","params":{"OBJNAM":"b0269","LISTORD":"4","PARENT":"R5C82","CIRCUIT":"00000"}},{"objnam":"b8AFB","params":{"OBJNAM":"b8AFB","LISTORD":"3","PARENT":"R5C82","CIRCUIT":"00000"}},{"objnam":"bAB0B","params":{"OBJNAM":"bAB0B","LISTORD":"2","PARENT":"R5C82","CIRCUIT":"00000"}},{"objnam":"b4292","params":{"OBJNAM":"b4292","LISTORD":"1","PARENT":"R5C82","CIRCUIT":"00000"}}]}}],"queryName":"GetRemotes","command":"SendQuery","messageID":"a861227b-6944-4407-b4eb-6613b6a939b9","response":"200"}

**Comment by gryz** [comment]
Could someone please update as to what the question is here the question is referring to?

**Comment by acarnagey** [comment]
The question is I still can't turn circuit affects that belong to a group to ACT 'OFF', shouldn't I be able to turn ACT to OFF for a circuit group's circuitAffect?  If yes then it is not working please see above comment, if no then how are we supposed to turn a circuit off or on as mentioned in the story for this?

**Comment by gryz** [comment]
Keith,

I think this is in your court. Could you please provide an answer to Adam's question.

**Comment by klewis77** [comment]
**We can use SetParamList using the Affect's Object Name**
Testing was done on DEV1

Using this group from GetHardwareDefinition
```json
{
                        "objnam": "CBE78",
                        "params": {
                            "OBJTYP": "CIRCUIT",
                            "SUBTYP": "CIRCGRP",
                            "HNAME": "Circ Group 1",
                            "SNAME": "tjRb",
                            "LISTORD": "12",
                            "PARENT": "00000",
                            "BODY": "00000",
                            "FREEZE": "OFF",
                            "VER": "VER",
                            "TIMZON": "TIMZON",
                            "TIME": "720",
                            "RLY": "RLY",
                            "DNTSTP": "OFF",
                            "FEATR": "ON",
                            "OBJLIST": [
                                {
                                    "objnam": "c6694",
                                    "params": {
                                        "OBJTYP": "CIRCGRP",
                                        "CIRCUIT": "C705E",
                                        "ACT": "ON",
                                        "LISTORD": "1",
                                        "DLY": "0"
                                    }
                                },
                                {
                                    "objnam": "cA83A",
                                    "params": {
                                        "OBJTYP": "CIRCGRP",
                                        "CIRCUIT": "CF28B",
                                        "ACT": "ON",
                                        "LISTORD": "1",
                                        "DLY": "0"
                                    }
                                }
                            ]
                        }
                    }
```
 **SetParamList Sent**
```json
{
    "command": "SetParamList", 
    "messageID": "10A86ef1-88f1-8091-7cdf1f", 
    "objectList": [
        {
            "objnam": "cA83A", 
            "params": {
                "ACT": "OFF" 
            }
        }
    ]
}

{
    "command": "SetParamList",
    "messageID": "10A86ef1-88f1-8091-7cdf1f",
    "response": "200"
}

{
    "command": "WriteParamList",
    "messageID": "1b87fdf8-cc4d-4816-8e1d-f39f2ab7971b",
    "timeSince": "948831605",
    "timeNow": "948832508",
    "objectList": [
        {
            "changes": [
                {
                    "objnam": "cA83A",
                    "params": {
                        "ACT": "OFF"
                    }
                }
            ]
        }
    ]
}
```

**GetHardwareDefinition Verification**
```json
{
                        "objnam": "CBE78",
                        "params": {
                            "OBJTYP": "CIRCUIT",
                            "SUBTYP": "CIRCGRP",
                            "HNAME": "Circ Group 1",
                            "SNAME": "tjRb",
                            "LISTORD": "12",
                            "PARENT": "00000",
                            "BODY": "00000",
                            "FREEZE": "OFF",
                            "VER": "VER",
                            "TIMZON": "TIMZON",
                            "TIME": "720",
                            "RLY": "RLY",
                            "DNTSTP": "OFF",
                            "FEATR": "ON",
                            "OBJLIST": [
                                {
                                    "objnam": "c6694",
                                    "params": {
                                        "OBJTYP": "CIRCGRP",
                                        "CIRCUIT": "C705E",
                                        "ACT": "ON",
                                        "LISTORD": "1",
                                        "DLY": "0"
                                    }
                                },
                                {
                                    "objnam": "cA83A",
                                    "params": {
                                        "OBJTYP": "CIRCGRP",
                                        "CIRCUIT": "CF28B",
                                        "ACT": "OFF",
                                        "LISTORD": "1",
                                        "DLY": "0"
                                    }
                                }
                            ]
                        }
                    }
```

**Comment by acarnagey** [comment]
Verified setparamlist based on circuitaffect works, will use it in addition to the create and edit circuit group calls so that act could get set to off.
